apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # This annotation will handle the redirect from HTTP to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - eks.net
      secretName: letsencrypt-production-tls
  rules:
  - host: eks.starci.net
    http:
      paths:
      - backend:
          service:
            name: "service-2048"
            port:
              number: 80
        path: /
        pathType: Prefix
      